services:
  dictionary:
    image: minhkycho18/dictionary-app
    container_name: dictionary-container
    ports:
      - "8080:8080"
    networks:
      - dev
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: dictionary-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vocab_note
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - dictionary-mysql-data:/var/lib/mysql
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  dictionary-mysql-data: